"""create queries table

Revision ID: d387f8b5573f
Revises: 
Create Date: 2025-07-26 00:42:41.116167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd387f8b5573f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_manuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='手順書の情報を格納するテーブル'
    )
    op.create_index(op.f('ix_t_manuals_title'), 't_manuals', ['title'], unique=False)
    op.create_index(op.f('ix_t_manuals_url'), 't_manuals', ['url'], unique=False)
    op.create_table('t_manual_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manual_id', sa.Integer(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manual_id'], ['t_manuals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='手順書のクエリ情報を格納するテーブル'
    )
    op.create_index(op.f('ix_t_manual_queries_query'), 't_manual_queries', ['query'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_manual_queries_query'), table_name='t_manual_queries')
    op.drop_table('t_manual_queries')
    op.drop_index(op.f('ix_t_manuals_url'), table_name='t_manuals')
    op.drop_index(op.f('ix_t_manuals_title'), table_name='t_manuals')
    op.drop_table('t_manuals')
    # ### end Alembic commands ###
